name: Builder
run-name: deploy
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - run: composer install
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: /package-lock.json
      - run: cd /var/www/html/hackathon
      - run: node -v
      - run: npm install
      - run: npm run dev
