name: Builder
run-name: deploy
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/master'
    steps:
      - run: composer install
#      - uses: actions/setup-node@v3
#        with:
#          node-version: 16
#      - run: cd /var/www/html/hackathon
#      - run: node -v
      - run: npm install
      - run: npm run dev

