name: Builder
run-name: deploy
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - run: echo "${{ github.actor }} start deploy 🚀"
      - run: composer install
      - run: npm install
      - run: npm run dev
